#!/bin/sh

set -o nounset

if test "${TRACE:-false}" != 'false'
then
    set -o xtrace
fi

WORKDIR=${WORKDIR:-${PWD}}
cd "${WORKDIR}" || exit 101

DESTINATION=${1:-${DESTINATION:-'out'}}
mkdir -p "${DESTINATION}"

DOCKERFILE=${2:-DOCKERFILE:-'Dockerfile'}

if test -f "${DOCKERFILE}"
then
    cp "${DOCKERFILE}" "${DESTINATION}"
    cp -r "$(dirname "${DOCKERFILE}")"/* "${DESTINATION}"
fi

find "${WORKDIR}" -type d -mindepth 1 -maxdepth 1 -exec basename '{}' \; | grep -v "^${DESTINATION}\$" | while read -r INPUT
do
    cp -r "${INPUT}" "${DESTINATION}/${INPUT}"
done
