---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: colstrom/alpine

inputs:
  - name: process

outputs:
  - name: command

run:
  path: sh
  args:
    - -c 'tar cC process/command . | tar xC command'
