---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: colstrom/alpine

inputs:
  - name: process

outputs:
  - name: command

run:
  path: process/command/duplicate
  args:
    - process/command
    - command
