---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: colstrom/alpine

inputs:
  - name: process
    path: ci

outputs:
  - name: archive

run:
  path: ci/command/fetch-archive
