---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: colstrom/riemann
    tag: build

inputs:
  - name: command

outputs:
  - name: archive

run:
  path: command/fetch-archive
